profile: cnc
project_code: cdk-handler-test
region: us-west-2
template_bucket_name: !stack_output assets-bucket.yaml::BucketName
template_key_prefix: "templates"
# If you use an iam_role, it will be the default role used to deploy when using the bootstrapless
# deployment_type (unless a different role is specified in the bootstrapless_config). If using the
# "bootstrapped" deployment_type with an iam_role, that role will first be assumed and then CDK will
# assume the bootstrapped roles for pushing image assets. The iam_role will always be used for
# actually deploying the synthesized stack templates, however.
iam_role: "arn:aws:iam::12345643232:role/my-deployment-role"
#account_id: 123456789012
#profile: account1
#cdk_context:
#  # CDK Bootstrap Qualifier
#  '@aws-cdk/core:bootstrapQualifier': hnb659fds
#
#  # CDK Feature Flags
#  '@aws-cdk/aws-lambda:recognizeLayerVersion': true
#  '@aws-cdk/core:checkSecretUsage': true
#  '@aws-cdk/core:target-partitions':
#    - aws
#    - aws-cn
#  '@aws-cdk-containers/ecs-service-extensions:enableDefaultLogDriver': true
#  '@aws-cdk/aws-ec2:uniqueImdsv2TemplateName': true
#  '@aws-cdk/aws-ecs:arnFormatIncludesClusterName': true
#  '@aws-cdk/aws-iam:minimizePolicies': true
#  '@aws-cdk/core:validateSnapshotRemovalPolicy': true
#  '@aws-cdk/aws-codepipeline:crossAccountKeyAliasStackSafeResourceName': true
#  '@aws-cdk/aws-s3:createDefaultLoggingPolicy': true
#  '@aws-cdk/aws-sns-subscriptions:restrictSqsDescryption': true
#  '@aws-cdk/aws-apigateway:disableCloudWatchRole': true
#  '@aws-cdk/core:enablePartitionLiterals': true
#  '@aws-cdk/aws-events:eventsTargetQueueSameAccount': true
#  '@aws-cdk/aws-iam:standardizedServicePrincipals': true
#  '@aws-cdk/aws-ecs:disableExplicitDeploymentControllerForCircuitBreaker': true
