region: eu-west-1
project_code: sceptre
account_id: 437373743264
profile: account1
cdk_context:
  # CDK Bootstrap Qualifier
  '@aws-cdk/core:bootstrapQualifier': hnb659fds

  # CDK Feature Flags
  '@aws-cdk/aws-lambda:recognizeLayerVersion': true
  '@aws-cdk/core:checkSecretUsage': true
  '@aws-cdk/core:target-partitions':
    - aws
    - aws-cn
  '@aws-cdk-containers/ecs-service-extensions:enableDefaultLogDriver': true
  '@aws-cdk/aws-ec2:uniqueImdsv2TemplateName': true
  '@aws-cdk/aws-ecs:arnFormatIncludesClusterName': true
  '@aws-cdk/aws-iam:minimizePolicies': true
  '@aws-cdk/core:validateSnapshotRemovalPolicy': true
  '@aws-cdk/aws-codepipeline:crossAccountKeyAliasStackSafeResourceName': true
  '@aws-cdk/aws-s3:createDefaultLoggingPolicy': true
  '@aws-cdk/aws-sns-subscriptions:restrictSqsDescryption': true
  '@aws-cdk/aws-apigateway:disableCloudWatchRole': true
  '@aws-cdk/core:enablePartitionLiterals': true
  '@aws-cdk/aws-events:eventsTargetQueueSameAccount': true
  '@aws-cdk/aws-iam:standardizedServicePrincipals': true
  '@aws-cdk/aws-ecs:disableExplicitDeploymentControllerForCircuitBreaker': true
